# ctx — context management targets
# Generated by: ctx init
# Safe to overwrite: ctx owns this file. Customize your Makefile, not this one.

.PHONY: journal journal-serve

## journal: Import sessions and regenerate journal site
journal:
	@echo "==> Importing sessions to journal..."
	@ctx journal import --all
	@echo "==> Generating journal site..."
	@ctx journal site --build
	@echo ""
	@echo "Journal site updated!"
	@echo ""
	@echo "Next steps (in Claude Code):"
	@echo "  /ctx-journal-enrich-all  — imports if needed + adds metadata per entry"
	@echo ""
	@echo "Then re-run: make journal"

## journal-serve: Serve the journal site locally
journal-serve:
	@ctx journal site --serve
