[project]

site_name = "things: wtf?"
site_description = "all your things are belong to us!"
site_author = "Volkan Özçelik <me@volkan.io>"
site_url = "https://things.wtf/"
repo_url = "https://github.com/zerotohero-dev/things-wtf"
repo_name = "things-wtf"
copyright = """
Copyright &copy; 2026&ndash;present Volkan Özçelik.<br>
The content on this website is distributed under
<a href="https://creativecommons.org/licenses/by/4.0/deed.en"><strong>CC-BY-4.0</strong></a>.
"""

nav = [
  { "WTF" = "index.md" },
  { "About Me" = "volkan.md" },
  { "Index" = "things.md" },
  { "Kubernetes" = [
      "k8s/index.md",
      { "Velero" = "k8s/velero/index.md" },
      { "Headlamp" = "k8s/headlamp/index.md" },
  ]},
  { "Zensical" = "zensical/index.md"},
  { "Regular Expressions" = "regex/index.md"},
]

extra_css = ["stylesheets/extra.css"]
#extra_javascript = ["javascripts/extra.js"]

[project.theme]
#variant = "classic"
#custom_dir = "overrides"
#favicon = "images/favicon.png"
language = "en"
features = [
    "announce.dismiss",
    #"content.action.edit",
    #"content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    "navigation.expand",
    # "navigation.footer",
    # "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    # "navigation.prune",
    # "navigation.sections",
    # "navigation.tabs",
    #"navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
    "toc.integrate",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.font]
text = "JetBrains Mono"
code = "JetBrains Mono"

[project.theme.icon]
logo = "lucide/message-circle-question-mark"
repo = "fontawesome/brands/github"

[project.extra]
generator = false

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/zerotohero-dev/things-wtf"


